"""
Veo 3 Video Generator with ElevenLabs Voiceover Integration

Generates cinematic AI videos using Google Veo 3 with synchronized
voiceover from ElevenLabs. Used for atmospheric, concept-driven content.
"""

import os
import json
import requests
from typing import Dict, Any, Optional, List
from datetime import datetime
from utils.logger import log_info, log_error, log_warning


class Veo3Generator:
    """Generate cinematic videos using Veo 3 with ElevenLabs voiceover."""

    # Veo 3 optimal prompt length
    MIN_PROMPT_LENGTH = 100
    MAX_PROMPT_LENGTH = 400
    OPTIMAL_PROMPT_LENGTH = 200  # 150-300 is sweet spot

    # Duration constraints
    VEO_MAX_DURATION = 8  # seconds per generation

    # Visual style presets
    STYLE_PRESETS = {
        'cinematic': {
            'keywords': ['cinematic', 'shot on 35mm film', 'shallow DOF', 'professional lighting'],
            'camera': ['slow dolly', 'gentle pan', 'steady tracking'],
        },
        'documentary': {
            'keywords': ['documentary style', 'handheld', 'natural lighting', 'authentic'],
            'camera': ['observational', 'following', 'reactive'],
        },
        'atmospheric': {
            'keywords': ['moody', 'atmospheric', 'dramatic lighting', 'silhouette'],
            'camera': ['static wide', 'slow zoom', 'time-lapse'],
        },
        'energetic': {
            'keywords': ['dynamic', 'fast-paced', 'high energy', 'action'],
            'camera': ['quick cuts', 'tracking', 'low angle'],
        },
    }

    # Content categories for fitness/trainer content
    CONTENT_CATEGORIES = {
        'motivation_morning': {
            'description': 'Early morning gym atmosphere, dedication theme',
            'visual_elements': ['empty gym', 'dawn light', 'equipment silhouettes'],
            'mood': 'inspiring, peaceful determination',
        },
        'the_grind': {
            'description': 'Hard work, effort, dedication',
            'visual_elements': ['chalk dust', 'sweat', 'weights', 'intense focus'],
            'mood': 'gritty, powerful, determined',
        },
        'transformation': {
            'description': 'Change, growth, before/after metaphor',
            'visual_elements': ['transitions', 'organization', 'progress'],
            'mood': 'hopeful, accomplished',
        },
        'client_journey': {
            'description': 'The experience of working with a trainer',
            'visual_elements': ['gym entrance', 'equipment', 'community'],
            'mood': 'welcoming, professional',
        },
        'lifestyle': {
            'description': 'Trainer lifestyle, balance, success',
            'visual_elements': ['modern spaces', 'technology', 'wellness'],
            'mood': 'aspirational, balanced',
        },
    }

    def __init__(self, config: Dict[str, Any] = None):
        """Initialize Veo 3 generator.

        Args:
            config: Optional configuration dictionary
        """
        self.config = config or {}
        self.elevenlabs_api_key = os.getenv('ELEVENLABS_API_KEY')
        self.elevenlabs_voice_id = os.getenv('ELEVENLABS_VOICE_ID')

        # Veo 3 API configuration (placeholder - update with actual API)
        self.veo_api_key = os.getenv('VEO_API_KEY')
        self.veo_endpoint = os.getenv('VEO_ENDPOINT', 'https://api.veo.google.com/v1')

    def generate_voiceover_script(
        self,
        duration_seconds: int,
        theme: str,
        style: str = 'motivational'
    ) -> Dict[str, Any]:
        """Generate a voiceover script for the specified duration.

        Args:
            duration_seconds: Target duration in seconds
            theme: Content theme (motivation_morning, the_grind, etc.)
            style: Script style (motivational, educational, storytelling)

        Returns:
            Dict with script text, word count, and timing
        """
        # Calculate word count based on duration
        # Average speaking rate: 2.5-3 words per second for impactful delivery
        words_per_second = 2.5
        target_words = int(duration_seconds * words_per_second)

        # Get theme configuration
        theme_config = self.CONTENT_CATEGORIES.get(theme, self.CONTENT_CATEGORIES['motivation_morning'])

        log_info(f"Generating {duration_seconds}s voiceover script for theme: {theme}")

        return {
            'theme': theme,
            'duration_seconds': duration_seconds,
            'target_word_count': target_words,
            'mood': theme_config['mood'],
            'style': style,
            # Script will be generated by Claude in content_generator
            'script_prompt': self._build_voiceover_prompt(duration_seconds, theme_config, style)
        }

    def _build_voiceover_prompt(
        self,
        duration: int,
        theme_config: Dict,
        style: str
    ) -> str:
        """Build the prompt for generating voiceover script.

        Args:
            duration: Duration in seconds
            theme_config: Theme configuration dictionary
            style: Script style

        Returns:
            Prompt string for script generation
        """
        word_count = int(duration * 2.5)

        return f"""
Generate a voiceover script for a {duration}-second cinematic fitness video.

THEME: {theme_config['description']}
MOOD: {theme_config['mood']}
STYLE: {style}
TARGET WORD COUNT: {word_count} words (±5 words)

SCRIPT GUIDELINES:
- Poetic, evocative language that paints pictures
- Short, punchy sentences with natural rhythm
- Must sound powerful when spoken aloud
- End with a strong statement or thought-provoking question
- Write for the EAR, not the eye

VOICE CHARACTERISTICS:
- Confident but warm
- Slightly intimate, like sharing a secret
- Measured pace with strategic pauses
- No rushing - let words breathe

AVOID:
- Clichés ("believe in yourself", "never give up")
- Long complex sentences
- Industry jargon
- Questions that don't add impact

EXAMPLE SCRIPTS BY DURATION:

8 seconds (~20 words):
"While they sleep, you rise. While they scroll, you build. This is the trainer's hour."

15 seconds (~38 words):
"Success isn't loud. It's the quiet reps when no one's watching. The early mornings. The late check-ins. The relentless pursuit of better. That's the trainer's path."

30 seconds (~75 words):
"They don't just hire us for sets and reps. They hire us for belief. For someone who sees their potential when they can't. For accountability when motivation fades. We're not just trainers. We're the bridge between who they are and who they're becoming. And that? That's worth every 5am alarm."

OUTPUT: Just the script text, nothing else.
"""

    def build_veo_prompt(
        self,
        category: str,
        style: str = 'cinematic',
        custom_elements: Dict[str, Any] = None
    ) -> str:
        """Build an optimized Veo 3 prompt.

        Args:
            category: Content category (motivation_morning, the_grind, etc.)
            style: Visual style preset
            custom_elements: Optional custom visual elements

        Returns:
            Optimized prompt string for Veo 3
        """
        # Get configurations
        category_config = self.CONTENT_CATEGORIES.get(category, self.CONTENT_CATEGORIES['motivation_morning'])
        style_config = self.STYLE_PRESETS.get(style, self.STYLE_PRESETS['cinematic'])

        # Build prompt components
        scene = self._build_scene_description(category_config, custom_elements)
        visual_style = ', '.join(style_config['keywords'])
        camera = style_config['camera'][0]  # Primary camera movement

        # Add audio direction
        audio = self._get_audio_direction(category)

        # Construct prompt
        prompt = f"{scene} {visual_style}. {camera} camera movement. {audio}"

        # Validate length
        if len(prompt) < self.MIN_PROMPT_LENGTH:
            prompt = self._expand_prompt(prompt, category_config)
        elif len(prompt) > self.MAX_PROMPT_LENGTH:
            prompt = self._condense_prompt(prompt)

        log_info(f"Built Veo 3 prompt ({len(prompt)} chars): {prompt[:100]}...")

        return prompt

    def _build_scene_description(
        self,
        category_config: Dict,
        custom_elements: Dict = None
    ) -> str:
        """Build the scene description portion of the prompt."""
        elements = custom_elements or {}
        visual_elements = elements.get('visual_elements', category_config['visual_elements'])

        # Build scene from elements
        scene_parts = []
        for element in visual_elements[:3]:  # Limit to 3 key elements
            scene_parts.append(element)

        return f"A {category_config['mood']} scene featuring {', '.join(scene_parts)}"

    def _get_audio_direction(self, category: str) -> str:
        """Get audio direction for the category."""
        audio_map = {
            'motivation_morning': 'Ambient gym sounds, distant weights, quiet determination',
            'the_grind': 'Heavy breathing, chalk dust, intense focus sounds',
            'transformation': 'Subtle uplifting music undertone, sounds of progress',
            'client_journey': 'Welcoming gym atmosphere, community energy',
            'lifestyle': 'Modern, clean ambient sounds, professional environment',
        }
        return audio_map.get(category, 'Natural ambient sounds')

    def _expand_prompt(self, prompt: str, category_config: Dict) -> str:
        """Expand a short prompt with more detail."""
        additions = [
            f"The mood is {category_config['mood']}.",
            "Shot in high definition with professional color grading.",
            "Natural lighting creates depth and atmosphere.",
        ]
        expanded = prompt + ' ' + ' '.join(additions[:2])
        return expanded

    def _condense_prompt(self, prompt: str) -> str:
        """Condense a long prompt to optimal length."""
        # Simple approach: truncate at last complete sentence before limit
        if len(prompt) <= self.MAX_PROMPT_LENGTH:
            return prompt

        truncated = prompt[:self.MAX_PROMPT_LENGTH]
        last_period = truncated.rfind('.')
        if last_period > self.MIN_PROMPT_LENGTH:
            return truncated[:last_period + 1]
        return truncated

    def generate_elevenlabs_audio(
        self,
        script: str,
        voice_id: str = None
    ) -> Optional[Dict[str, Any]]:
        """Generate voiceover audio using ElevenLabs.

        Args:
            script: The voiceover script text
            voice_id: Optional voice ID override

        Returns:
            Dict with audio URL and metadata, or None on failure
        """
        if not self.elevenlabs_api_key:
            log_error("ElevenLabs API key not configured")
            return None

        voice = voice_id or self.elevenlabs_voice_id
        if not voice:
            log_error("ElevenLabs voice ID not configured")
            return None

        try:
            url = f"https://api.elevenlabs.io/v1/text-to-speech/{voice}"

            headers = {
                "Accept": "audio/mpeg",
                "Content-Type": "application/json",
                "xi-api-key": self.elevenlabs_api_key
            }

            data = {
                "text": script,
                "model_id": "eleven_monolingual_v1",
                "voice_settings": {
                    "stability": 0.5,
                    "similarity_boost": 0.75,
                    "style": 0.5,  # For eleven_multilingual_v2
                    "use_speaker_boost": True
                }
            }

            response = requests.post(url, json=data, headers=headers, timeout=30)

            if response.status_code == 200:
                # Save audio to temp file or upload to storage
                audio_filename = f"voiceover_{datetime.now().strftime('%Y%m%d_%H%M%S')}.mp3"

                log_info(f"Generated ElevenLabs audio: {len(response.content)} bytes")

                return {
                    'audio_content': response.content,
                    'filename': audio_filename,
                    'script': script,
                    'voice_id': voice,
                    'word_count': len(script.split()),
                    'estimated_duration': len(script.split()) / 2.5  # Approximate
                }
            else:
                log_error(f"ElevenLabs API error: {response.status_code} - {response.text}")
                return None

        except Exception as e:
            log_error(f"ElevenLabs generation failed: {e}")
            return None

    def get_veo_prompt_templates(self) -> Dict[str, str]:
        """Get pre-built Veo 3 prompt templates for common scenarios.

        Returns:
            Dict of template name to prompt string
        """
        return {
            'motivation_morning': """
A cinematic wide shot of an empty gym at dawn, golden hour light streaming through large windows, dust particles floating in light beams, slow dolly forward movement. Ambient sound of distant weights and motivational energy. Shot on 35mm film look, shallow depth of field.
""".strip(),

            'the_grind': """
Close-up slow motion of hands chalking up before a lift, dramatic side lighting creating strong shadows, shallow depth of field, chalk particles suspended in air. Sound of deep breath and focused exhale. Gritty, documentary style with film grain.
""".strip(),

            'transformation': """
Time-lapse style transition from cluttered desk with scattered papers to organized minimal workspace with laptop and plant. Warm natural lighting shifting from harsh to soft. Subtle ambient music undertone. Clean, professional aesthetic.
""".strip(),

            'client_journey': """
POV shot walking into a modern gym, camera at chest height moving steadily forward, passing equipment and focused athletes, warm welcoming lighting with morning sun. Sounds of gym activity, upbeat ambient energy. Cinematic handheld style with gentle stabilization.
""".strip(),

            'evening_reflection': """
Wide shot of empty gym at sunset, long shadows across equipment, single figure stretching in silhouette against window light. Peaceful, accomplished mood. Slow gentle pan. Quiet ambient sounds, distant city hum. Cinematic color grading with warm tones.
""".strip(),
        }


# Export for use in content pipeline
__all__ = ['Veo3Generator']
