#!/usr/bin/env python3
"""Upload Refiloe reference images to Leonardo AI.

This script uploads 6 specific reference images of Refiloe to Leonardo AI
and generates a Python constants file with the returned image IDs.

Usage:
    python scripts/upload_refiloe_references.py

The script will:
1. Upload 6 images from /mnt/user-data/uploads/
2. Print the ID for each uploaded image
3. Generate constants file code for social_media/refiloe_reference_ids.py
"""

import os
import sys
import requests
from pathlib import Path


LEONARDO_API_BASE = "https://cloud.leonardo.ai/api/rest/v1"
UPLOADS_DIR = "/Users/Howard/Downloads/"

# Define the 6 reference images with descriptive names
REFERENCE_IMAGES = [
    {
        "filename": "universal_upscale_0_0fd6ed69-9bd0-4239-b6bd-5a142cd94e2f_0.jpg",
        "const_name": "CASUAL_SMILE",
        "description": "Casual smile - friendly approachable look"
    },
    {
        "filename": "universal_upscale_0_1b97a903-d0ed-4b0d-aa03-2716bf451f70_0.jpg",
        "const_name": "PROFESSIONAL_CONFIDENT",
        "description": "Professional arms crossed - confident business look"
    },
    {
        "filename": "universal_upscale_0_183a0e60-99bc-4639-b2db-786d3e9efad8_0.jpg",
        "const_name": "WHITE_SHIRT_PORTRAIT",
        "description": "White shirt portrait - clean professional headshot"
    },
    {
        "filename": "universal_upscale_0_8dc1af1f-01ca-4aa9-a8a3-99ff31b6da66_0.jpg",
        "const_name": "ATHLETIC_BRANDING",
        "description": "Athletic with branding - sporty branded appearance"
    },
    {
        "filename": "universal_upscale_0_c67d679c-a7f1-4870-9fbd-1aa59eae6d2b_0.jpg",
        "const_name": "DENIM_JACKET_URBAN",
        "description": "Denim jacket urban - casual street style"
    },
    {
        "filename": "universal_upscale_0_49b7f32e-f5ac-45e2-ba26-d605df54f846_0.jpg",
        "const_name": "BOMBER_JACKET_URBAN",
        "description": "Bomber jacket urban - modern urban fashion"
    }
]


def upload_image(file_path: str, api_key: str) -> str:
    """Upload image to Leonardo AI and return image ID.

    Args:
        file_path: Path to the image file to upload.
        api_key: Leonardo API key.

    Returns:
        The Leonardo AI image ID.

    Raises:
        ValueError: If file doesn't exist.
        requests.RequestException: If upload fails.
    """
    if not os.path.exists(file_path):
        raise ValueError(f"File not found: {file_path}")

    # Determine file extension
    file_ext = os.path.splitext(file_path)[1].lower()
    if file_ext in ['.jpg', '.jpeg']:
        extension = 'jpg'
    elif file_ext == '.png':
        extension = 'png'
    else:
        extension = 'jpg'

    # Prepare multipart upload
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Accept": "application/json",
    }

    try:
        with open(file_path, 'rb') as image_file:
            files = {
                'file': (os.path.basename(file_path), image_file, f'image/{extension}')
            }
            data = {
                'extension': extension
            }

            response = requests.post(
                f"{LEONARDO_API_BASE}/init-image",
                headers=headers,
                files=files,
                data=data,
                timeout=60,
            )
            response.raise_for_status()

    except requests.Timeout:
        raise requests.RequestException("Upload timed out. Please try again.")
    except requests.RequestException as e:
        error_msg = f"Upload failed: {e}"
        if hasattr(e, 'response') and e.response is not None:
            try:
                error_detail = e.response.json()
                error_msg += f"\nAPI Error: {error_detail}"
            except:
                error_msg += f"\nResponse: {e.response.text}"
        raise requests.RequestException(error_msg)

    # Parse response
    result = response.json()

    # Extract image ID from response
    # Leonardo API returns: {"uploadInitImage": {"id": "..."}}
    upload_data = result.get("uploadInitImage", {})
    image_id = upload_data.get("id")

    if not image_id:
        raise ValueError(f"No image ID in response: {result}")

    return image_id


def generate_constants_file(uploaded_images: list) -> str:
    """Generate Python code for the constants file.

    Args:
        uploaded_images: List of dicts with const_name, description, and image_id.

    Returns:
        Python code as a string.
    """
    code_lines = [
        '"""Refiloe reference image IDs for Leonardo AI.',
        '',
        'These image IDs were generated by scripts/upload_refiloe_references.py',
        'and represent different looks/poses of Refiloe for character consistency.',
        '"""',
        '',
        '# All reference image IDs',
        'REFILOE_REFERENCE_IDS = ['
    ]

    # Add all IDs to the list
    for img in uploaded_images:
        code_lines.append(f'    "{img["image_id"]}",  # {img["description"]}')

    code_lines.append(']')
    code_lines.append('')
    code_lines.append('# Individual constants for specific looks')

    # Add individual constants
    for img in uploaded_images:
        code_lines.append(f'# {img["description"]}')
        code_lines.append(f'{img["const_name"]} = "{img["image_id"]}"')
        code_lines.append('')

    return '\n'.join(code_lines)


def main():
    """Main entry point."""
    # Get API key from environment
    api_key = os.getenv("LEONARDO_API_KEY")
    if not api_key:
        print("✗ Error: LEONARDO_API_KEY environment variable is required.")
        print("\nGet your API key from: https://leonardo.ai/ → Settings → API")
        return 1

    print("="*60)
    print("Uploading Refiloe Reference Images to Leonardo AI")
    print("="*60)
    print(f"\nTotal images to upload: {len(REFERENCE_IMAGES)}")
    print(f"Upload directory: {UPLOADS_DIR}\n")

    uploaded_images = []
    failed_uploads = []

    # Upload each image
    for idx, img_info in enumerate(REFERENCE_IMAGES, 1):
        file_path = os.path.join(UPLOADS_DIR, img_info["filename"])

        print(f"[{idx}/{len(REFERENCE_IMAGES)}] Uploading: {img_info['description']}")
        print(f"    File: {img_info['filename']}")

        try:
            image_id = upload_image(file_path, api_key)
            print(f"    ✓ Success! Image ID: {image_id}\n")

            uploaded_images.append({
                "const_name": img_info["const_name"],
                "description": img_info["description"],
                "image_id": image_id,
                "filename": img_info["filename"]
            })

        except Exception as e:
            print(f"    ✗ Failed: {e}\n")
            failed_uploads.append({
                "filename": img_info["filename"],
                "error": str(e)
            })

    # Print summary
    print("="*60)
    print("Upload Summary")
    print("="*60)
    print(f"Successful: {len(uploaded_images)}/{len(REFERENCE_IMAGES)}")
    print(f"Failed: {len(failed_uploads)}/{len(REFERENCE_IMAGES)}")

    if failed_uploads:
        print("\nFailed uploads:")
        for fail in failed_uploads:
            print(f"  - {fail['filename']}: {fail['error']}")

    # Generate constants file if we have any successful uploads
    if uploaded_images:
        print("\n" + "="*60)
        print("Generated Constants File Content")
        print("="*60)
        print("\nCopy the following to: social_media/refiloe_reference_ids.py\n")
        print("-"*60)

        constants_code = generate_constants_file(uploaded_images)
        print(constants_code)

        print("-"*60)
        print("\nTo use these reference IDs, import them in your code:")
        print("  from social_media.refiloe_reference_ids import REFILOE_REFERENCE_IDS")
        print("  from social_media.refiloe_reference_ids import CASUAL_SMILE")
        print("="*60)

    return 0 if len(failed_uploads) == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
